### ISSUE TITLE
Can work with itkpi site

### ISSUE THREAD

**Issue by MaxymVlasov** [itkpi/fortuna-incognita#1]
For example,  share post on social networks

**Comment by webknjaz** [comment]
Excuse me, how does the issue title match its description?

**Comment by MaxymVlasov** [comment]
In description I wrote mechanism, how can implement issue

**Comment by webknjaz** [comment]
I do not see any description

**Comment by MaxymVlasov** [comment]
Okay

> Є сторінка з івентом, десь на itkpi.pp.ua/events/event/100500
> 
> На сторінці написано "розіграємо 100500 білетиків за розшарювання інфи про івент через соц. мережі"
> Від цими солвами стоять кнопочки шерингу.
> 
> Хто не вкурсі - ті кнопочки якось знають скільки народу через них пошарило, бо якщо видалити шер - то кнопка про це знатиме.
> 
> Так от, витягти через АПІ якось список пошаривших і зробити по ним розіграш.
> 
> ВСЕ.

**Comment by MaxymVlasov** [comment]
No longer relevant.
